sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-5
      - libboost1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-program-options1.55-dev
      - libhdf5-serial-dev

install:
  - export CXX="g++-5"

script:
  - mkdir -p build/{debug,release}
  - cd build/debug
  - cmake ../.. -DCMAKE_BUILD_TYPE=Debug
  - make trento test-trento
  - ./test/test-trento --success
  - ./src/trento p Pb 10
  - ./src/trento Cu2 Au2 10
  - cd ../release
  - cmake ../.. -DCMAKE_BUILD_TYPE=Release
  - make trento test-trento
  - ./test/test-trento --success
  - ./src/trento p Pb 10
  - ./src/trento U U 10
