language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.9 libboost1.55-dev libboost-{filesystem,program-options}1.55-dev libhdf5-serial-dev
  - export CXX="g++-4.9"

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make trento test-trento
  - ./test/test-trento --success
  - ./src/trento p Pb 10
  - ./src/trento U U 10
